// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TimeSlotAllocation.
const (
	ACTUAL TimeSlotAllocation = "ACTUAL"
	PLAN   TimeSlotAllocation = "PLAN"
)

// Task defines model for Task.
type Task struct {
	CreatedAt   *time.Time         `json:"createdAt,omitempty"`
	CreatedBy   *string            `json:"createdBy,omitempty"`
	Description *string            `json:"description,omitempty"`
	TaskId      openapi_types.UUID `json:"taskId"`
	Title       string             `json:"title"`
	UpdatedAt   *time.Time         `json:"updatedAt,omitempty"`
	UpdatedBy   *string            `json:"updatedBy,omitempty"`
	UserId      string             `json:"userId"`
}

// TimeSlot defines model for TimeSlot.
type TimeSlot struct {
	// Allocation スロットのタイプ (PLAN=予定, ACTUAL=実績)
	Allocation  TimeSlotAllocation `json:"allocation"`
	CreatedBy   *string            `json:"createdBy,omitempty"`
	Description *string            `json:"description,omitempty"`
	EndAt       time.Time          `json:"endAt"`

	// ExtData 拡張データ
	ExtData *map[string]interface{} `json:"extData,omitempty"`
	StartAt time.Time               `json:"startAt"`

	// TaskId 紐づくタスクID (任意)
	TaskId *openapi_types.UUID `json:"taskId,omitempty"`

	// TimeSlotId タイムスロットID
	TimeSlotId openapi_types.UUID `json:"timeSlotId"`
	Title      *string            `json:"title,omitempty"`
	UpdatedBy  *string            `json:"updatedBy,omitempty"`

	// UserId ユーザーID (Email)
	UserId string `json:"userId"`
}

// TimeSlotAllocation スロットのタイプ (PLAN=予定, ACTUAL=実績)
type TimeSlotAllocation string

// TimeSlotList defines model for TimeSlotList.
type TimeSlotList struct {
	TimeSlots *[]TimeSlot `json:"timeSlots,omitempty"`
}

// GetTimeSlotsParams defines parameters for GetTimeSlots.
type GetTimeSlotsParams struct {
	StartAt time.Time `form:"startAt" json:"startAt"`
	EndAt   time.Time `form:"endAt" json:"endAt"`
}

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = Task

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = Task

// CreateTimeSlotJSONRequestBody defines body for CreateTimeSlot for application/json ContentType.
type CreateTimeSlotJSONRequestBody = TimeSlot

// UpdateTimeSlotJSONRequestBody defines body for UpdateTimeSlot for application/json ContentType.
type UpdateTimeSlotJSONRequestBody = TimeSlot

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// タスク一覧取得
	// (GET /tasks)
	GetTasks(w http.ResponseWriter, r *http.Request)
	// タスク作成
	// (POST /tasks)
	CreateTask(w http.ResponseWriter, r *http.Request)
	// タスク削除
	// (DELETE /tasks/{taskId})
	DeleteTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// タスク詳細取得
	// (GET /tasks/{taskId})
	GetTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// タスク更新
	// (PUT /tasks/{taskId})
	UpdateTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// タイムスロット一覧取得
	// (GET /timeSlots)
	GetTimeSlots(w http.ResponseWriter, r *http.Request, params GetTimeSlotsParams)
	// タイムスロット作成
	// (POST /timeSlots)
	CreateTimeSlot(w http.ResponseWriter, r *http.Request)
	// タイムスロット削除
	// (DELETE /timeSlots/{timeSlotId})
	DeleteTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID)
	// タイムスロット詳細取得
	// (GET /timeSlots/{timeSlotId})
	GetTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID)
	// タイムスロット更新
	// (PUT /timeSlots/{timeSlotId})
	UpdateTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// タスク一覧取得
// (GET /tasks)
func (_ Unimplemented) GetTasks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タスク作成
// (POST /tasks)
func (_ Unimplemented) CreateTask(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タスク削除
// (DELETE /tasks/{taskId})
func (_ Unimplemented) DeleteTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タスク詳細取得
// (GET /tasks/{taskId})
func (_ Unimplemented) GetTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タスク更新
// (PUT /tasks/{taskId})
func (_ Unimplemented) UpdateTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タイムスロット一覧取得
// (GET /timeSlots)
func (_ Unimplemented) GetTimeSlots(w http.ResponseWriter, r *http.Request, params GetTimeSlotsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タイムスロット作成
// (POST /timeSlots)
func (_ Unimplemented) CreateTimeSlot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タイムスロット削除
// (DELETE /timeSlots/{timeSlotId})
func (_ Unimplemented) DeleteTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タイムスロット詳細取得
// (GET /timeSlots/{timeSlotId})
func (_ Unimplemented) GetTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タイムスロット更新
// (PUT /timeSlots/{timeSlotId})
func (_ Unimplemented) UpdateTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetTasks operation middleware
func (siw *ServerInterfaceWrapper) GetTasks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTask operation middleware
func (siw *ServerInterfaceWrapper) DeleteTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", chi.URLParam(r, "taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", chi.URLParam(r, "taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTask operation middleware
func (siw *ServerInterfaceWrapper) UpdateTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", chi.URLParam(r, "taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimeSlots operation middleware
func (siw *ServerInterfaceWrapper) GetTimeSlots(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTimeSlotsParams

	// ------------- Required query parameter "startAt" -------------

	if paramValue := r.URL.Query().Get("startAt"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "startAt"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "startAt", r.URL.Query(), &params.StartAt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "startAt", Err: err})
		return
	}

	// ------------- Required query parameter "endAt" -------------

	if paramValue := r.URL.Query().Get("endAt"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "endAt"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "endAt", r.URL.Query(), &params.EndAt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endAt", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimeSlots(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTimeSlot operation middleware
func (siw *ServerInterfaceWrapper) CreateTimeSlot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTimeSlot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTimeSlot operation middleware
func (siw *ServerInterfaceWrapper) DeleteTimeSlot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timeSlotId" -------------
	var timeSlotId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "timeSlotId", chi.URLParam(r, "timeSlotId"), &timeSlotId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeSlotId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTimeSlot(w, r, timeSlotId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimeSlot operation middleware
func (siw *ServerInterfaceWrapper) GetTimeSlot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timeSlotId" -------------
	var timeSlotId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "timeSlotId", chi.URLParam(r, "timeSlotId"), &timeSlotId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeSlotId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimeSlot(w, r, timeSlotId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTimeSlot operation middleware
func (siw *ServerInterfaceWrapper) UpdateTimeSlot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timeSlotId" -------------
	var timeSlotId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "timeSlotId", chi.URLParam(r, "timeSlotId"), &timeSlotId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeSlotId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTimeSlot(w, r, timeSlotId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tasks", wrapper.GetTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tasks", wrapper.CreateTask)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/tasks/{taskId}", wrapper.DeleteTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tasks/{taskId}", wrapper.GetTask)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/tasks/{taskId}", wrapper.UpdateTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/timeSlots", wrapper.GetTimeSlots)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/timeSlots", wrapper.CreateTimeSlot)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/timeSlots/{timeSlotId}", wrapper.DeleteTimeSlot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/timeSlots/{timeSlotId}", wrapper.GetTimeSlot)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/timeSlots/{timeSlotId}", wrapper.UpdateTimeSlot)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXTW8TRxj+K9bbHoi0zZrSA1qJg0mqympEIzWcUA5T7xuysF/MzKJalqXGW6mhHJJL",
	"Q2krtZUotEIEJEJFSQo/ZmIH/kU1s9nvdbImcpqTvTv7fj3PM+8704OO5/ieiy5nYPSAdVbRIervEmE3",
	"5a9PPR8pt1C97VAkHM0Wlw8rHnUIBwNMwvEjbjkIGvCuj2AA49Ryr0Nfi00ud6VJadVE1qGWzy3PrVzn",
	"hN1sm7loQWCZVYG4xW2sdBL45qRZH5qMyTpgSKOsCkt9DSjeCiyKJhjX4uwTgzjJ5SSi99UN7HDpc8ly",
	"8Evb42XQiW17HRJD9CHFFTDgAz2lTj/kTY99tFKLEzOA7kTA4dd8nnAiDXKeYXT39+HeCxF+J8I9MXgD",
	"FRAwTiifJFiqjnysg51NsfaHWNsQgzdi8I8YPG3PN87t7+6Ovt2YAa2OliIgq5wrnw9E+Jv0HD4RYSjC",
	"9fZ8PbfHSPRYvRVSCR8qNP8W4Z6s8FOHWPZMOXJRlml1GWlmZJZSEfN/lGJbOX0WwUoxEmvbMXb3GucW",
	"F1pXLu2/Wh9u/6Q1WnNLV1sLl4bbvx68fD2jogaOTFV+BRpE65ksUmziLBYsVrF34lLVg8XRYXX3kOIr",
	"CkYoJV2FYgED+cpyV7xy3YuEEttGe47Y6JqEytrDTYnD4KkY/CnC5yK801ps7+/+MHr0Y9IYyoaN1mIb",
	"NLiNlEWez882Z5syOc9Hl/gWGHBhtjl7ATTwCV9V9elyY6h/11GBIiFRDEkVwWfIl9QHUhbM91wWgfVx",
	"s6mavOdydJUd8X3birjVb7CI4Aio+njKQVLGsth54IvPFcIscBxCu/E+k3t3/+U3bx8+Gm5sDV/fk558",
	"j1UUNae6nIoWqR0Zv+yZ3YkqOr6Q/F7iNMB+CcXzU4iZBysq1hyL2L+/jNY31WokBb0Xtcp+pFQbOZYR",
	"nFfvEwRzJX1SlvgVrzF3WOOYNIZ3vn93/4Gk7CgZnlSF74PfeLG9/ev5wc6zjNgIJQ5ypAyMaz2wpLXc",
	"Z6CBSxyp6GTI52WhZVI8ZjD0lzXwgwqErqqpcCY0/X9yMvp5Z7T17FDO2YY+VlbJR9UE3gqQdlMG02FX",
	"g8IjDiR9rdp/NEJP7H15mqRkp2htcoqnoIk6dTxnp6TsZIyfcsfOxa3dtUtIZjt4rGa9l57c6nTyLMIn",
	"6+bF9Gp09rHBm6eCdT3Bvke3z56dp9bxz9LeOEt8JZNAfor0dkxU8Vr0RF2LHovw8butuwf3X4nBC/lG",
	"nsD35J2H2mDAKue+oevy8mKveowbF5sXm9Bf7v8XAAD//7dSR3EXEQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
