// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Task defines model for Task.
type Task struct {
	CreatedAt       time.Time          `json:"createdAt"`
	CreatedBy       openapi_types.UUID `json:"createdBy"`
	TaskDescription *string            `json:"taskDescription,omitempty"`
	TaskId          openapi_types.UUID `json:"taskId"`
	Title           string             `json:"title"`
	UpdatedAt       time.Time          `json:"updatedAt"`
	UpdatedBy       openapi_types.UUID `json:"updatedBy"`
	UserId          openapi_types.UUID `json:"userId"`
}

// TimeSlot defines model for TimeSlot.
type TimeSlot struct {
	// Allocation アロケーション
	Allocation string             `json:"allocation"`
	CreatedAt  time.Time          `json:"createdAt"`
	CreatedBy  openapi_types.UUID `json:"createdBy"`
	EndAt      time.Time          `json:"endAt"`

	// ExtData 拡張データ
	ExtData *map[string]interface{} `json:"extData,omitempty"`
	StartAt time.Time               `json:"startAt"`

	// TaskId 紐づくタスクID
	TaskId openapi_types.UUID `json:"taskId"`

	// TimeSlotId タイムスロットID
	TimeSlotId openapi_types.UUID `json:"timeSlotId"`
	UpdatedAt  time.Time          `json:"updatedAt"`
	UpdatedBy  openapi_types.UUID `json:"updatedBy"`

	// UserId ユーザーID (Email)
	UserId openapi_types.UUID `json:"userId"`
}

// TimeSlotList defines model for TimeSlotList.
type TimeSlotList struct {
	TimeSlots *[]TimeSlot `json:"timeSlots,omitempty"`
}

// GetTasksParams defines parameters for GetTasks.
type GetTasksParams struct {
	UserId openapi_types.UUID `form:"userId" json:"userId"`
}

// GetTimeSlotsParams defines parameters for GetTimeSlots.
type GetTimeSlotsParams struct {
	UserId  openapi_types.UUID `form:"userId" json:"userId"`
	StartAt time.Time          `form:"startAt" json:"startAt"`
	EndAt   time.Time          `form:"endAt" json:"endAt"`
}

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = Task

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = Task

// CreateTimeSlotJSONRequestBody defines body for CreateTimeSlot for application/json ContentType.
type CreateTimeSlotJSONRequestBody = TimeSlot

// UpdateTimeSlotJSONRequestBody defines body for UpdateTimeSlot for application/json ContentType.
type UpdateTimeSlotJSONRequestBody = TimeSlot

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// タスク一覧取得
	// (GET /tasks)
	GetTasks(w http.ResponseWriter, r *http.Request, params GetTasksParams)
	// タスク作成
	// (POST /tasks)
	CreateTask(w http.ResponseWriter, r *http.Request)
	// タスク削除
	// (DELETE /tasks/{taskId})
	DeleteTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// タスク詳細取得
	// (GET /tasks/{taskId})
	GetTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// タスク更新
	// (PUT /tasks/{taskId})
	UpdateTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)
	// タイムスロット一覧取得
	// (GET /timeSlots)
	GetTimeSlots(w http.ResponseWriter, r *http.Request, params GetTimeSlotsParams)
	// タイムスロット作成
	// (POST /timeSlots)
	CreateTimeSlot(w http.ResponseWriter, r *http.Request)
	// タイムスロット削除
	// (DELETE /timeSlots/{timeSlotId})
	DeleteTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID)
	// タイムスロット詳細取得
	// (GET /timeSlots/{timeSlotId})
	GetTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID)
	// タイムスロット更新
	// (PUT /timeSlots/{timeSlotId})
	UpdateTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// タスク一覧取得
// (GET /tasks)
func (_ Unimplemented) GetTasks(w http.ResponseWriter, r *http.Request, params GetTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タスク作成
// (POST /tasks)
func (_ Unimplemented) CreateTask(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タスク削除
// (DELETE /tasks/{taskId})
func (_ Unimplemented) DeleteTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タスク詳細取得
// (GET /tasks/{taskId})
func (_ Unimplemented) GetTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タスク更新
// (PUT /tasks/{taskId})
func (_ Unimplemented) UpdateTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タイムスロット一覧取得
// (GET /timeSlots)
func (_ Unimplemented) GetTimeSlots(w http.ResponseWriter, r *http.Request, params GetTimeSlotsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タイムスロット作成
// (POST /timeSlots)
func (_ Unimplemented) CreateTimeSlot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タイムスロット削除
// (DELETE /timeSlots/{timeSlotId})
func (_ Unimplemented) DeleteTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タイムスロット詳細取得
// (GET /timeSlots/{timeSlotId})
func (_ Unimplemented) GetTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タイムスロット更新
// (PUT /timeSlots/{timeSlotId})
func (_ Unimplemented) UpdateTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetTasks operation middleware
func (siw *ServerInterfaceWrapper) GetTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTasksParams

	// ------------- Required query parameter "userId" -------------

	if paramValue := r.URL.Query().Get("userId"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "userId"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "userId", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTask operation middleware
func (siw *ServerInterfaceWrapper) DeleteTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", chi.URLParam(r, "taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", chi.URLParam(r, "taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTask operation middleware
func (siw *ServerInterfaceWrapper) UpdateTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", chi.URLParam(r, "taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTask(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimeSlots operation middleware
func (siw *ServerInterfaceWrapper) GetTimeSlots(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTimeSlotsParams

	// ------------- Required query parameter "userId" -------------

	if paramValue := r.URL.Query().Get("userId"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "userId"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "userId", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	// ------------- Required query parameter "startAt" -------------

	if paramValue := r.URL.Query().Get("startAt"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "startAt"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "startAt", r.URL.Query(), &params.StartAt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "startAt", Err: err})
		return
	}

	// ------------- Required query parameter "endAt" -------------

	if paramValue := r.URL.Query().Get("endAt"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "endAt"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "endAt", r.URL.Query(), &params.EndAt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endAt", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimeSlots(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTimeSlot operation middleware
func (siw *ServerInterfaceWrapper) CreateTimeSlot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTimeSlot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTimeSlot operation middleware
func (siw *ServerInterfaceWrapper) DeleteTimeSlot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timeSlotId" -------------
	var timeSlotId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "timeSlotId", chi.URLParam(r, "timeSlotId"), &timeSlotId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeSlotId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTimeSlot(w, r, timeSlotId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimeSlot operation middleware
func (siw *ServerInterfaceWrapper) GetTimeSlot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timeSlotId" -------------
	var timeSlotId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "timeSlotId", chi.URLParam(r, "timeSlotId"), &timeSlotId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeSlotId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimeSlot(w, r, timeSlotId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTimeSlot operation middleware
func (siw *ServerInterfaceWrapper) UpdateTimeSlot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timeSlotId" -------------
	var timeSlotId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "timeSlotId", chi.URLParam(r, "timeSlotId"), &timeSlotId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeSlotId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTimeSlot(w, r, timeSlotId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tasks", wrapper.GetTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tasks", wrapper.CreateTask)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/tasks/{taskId}", wrapper.DeleteTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tasks/{taskId}", wrapper.GetTask)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/tasks/{taskId}", wrapper.UpdateTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/timeSlots", wrapper.GetTimeSlots)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/timeSlots", wrapper.CreateTimeSlot)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/timeSlots/{timeSlotId}", wrapper.DeleteTimeSlot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/timeSlots/{timeSlotId}", wrapper.GetTimeSlot)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/timeSlots/{timeSlotId}", wrapper.UpdateTimeSlot)
	})

	return r
}

type GetTasksRequestObject struct {
	Params GetTasksParams
}

type GetTasksResponseObject interface {
	VisitGetTasksResponse(w http.ResponseWriter) error
}

type GetTasks200JSONResponse []Task

func (response GetTasks200JSONResponse) VisitGetTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateTaskRequestObject struct {
	Body *CreateTaskJSONRequestBody
}

type CreateTaskResponseObject interface {
	VisitCreateTaskResponse(w http.ResponseWriter) error
}

type CreateTask201JSONResponse Task

func (response CreateTask201JSONResponse) VisitCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTaskRequestObject struct {
	TaskId openapi_types.UUID `json:"taskId"`
}

type DeleteTaskResponseObject interface {
	VisitDeleteTaskResponse(w http.ResponseWriter) error
}

type DeleteTask204Response struct {
}

func (response DeleteTask204Response) VisitDeleteTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetTaskRequestObject struct {
	TaskId openapi_types.UUID `json:"taskId"`
}

type GetTaskResponseObject interface {
	VisitGetTaskResponse(w http.ResponseWriter) error
}

type GetTask200JSONResponse Task

func (response GetTask200JSONResponse) VisitGetTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTask404JSONResponse Error

func (response GetTask404JSONResponse) VisitGetTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTaskRequestObject struct {
	TaskId openapi_types.UUID `json:"taskId"`
	Body   *UpdateTaskJSONRequestBody
}

type UpdateTaskResponseObject interface {
	VisitUpdateTaskResponse(w http.ResponseWriter) error
}

type UpdateTask200JSONResponse Task

func (response UpdateTask200JSONResponse) VisitUpdateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTimeSlotsRequestObject struct {
	Params GetTimeSlotsParams
}

type GetTimeSlotsResponseObject interface {
	VisitGetTimeSlotsResponse(w http.ResponseWriter) error
}

type GetTimeSlots200JSONResponse TimeSlotList

func (response GetTimeSlots200JSONResponse) VisitGetTimeSlotsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateTimeSlotRequestObject struct {
	Body *CreateTimeSlotJSONRequestBody
}

type CreateTimeSlotResponseObject interface {
	VisitCreateTimeSlotResponse(w http.ResponseWriter) error
}

type CreateTimeSlot201JSONResponse TimeSlot

func (response CreateTimeSlot201JSONResponse) VisitCreateTimeSlotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTimeSlotRequestObject struct {
	TimeSlotId openapi_types.UUID `json:"timeSlotId"`
}

type DeleteTimeSlotResponseObject interface {
	VisitDeleteTimeSlotResponse(w http.ResponseWriter) error
}

type DeleteTimeSlot204Response struct {
}

func (response DeleteTimeSlot204Response) VisitDeleteTimeSlotResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetTimeSlotRequestObject struct {
	TimeSlotId openapi_types.UUID `json:"timeSlotId"`
}

type GetTimeSlotResponseObject interface {
	VisitGetTimeSlotResponse(w http.ResponseWriter) error
}

type GetTimeSlot200JSONResponse TimeSlot

func (response GetTimeSlot200JSONResponse) VisitGetTimeSlotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTimeSlotRequestObject struct {
	TimeSlotId openapi_types.UUID `json:"timeSlotId"`
	Body       *UpdateTimeSlotJSONRequestBody
}

type UpdateTimeSlotResponseObject interface {
	VisitUpdateTimeSlotResponse(w http.ResponseWriter) error
}

type UpdateTimeSlot200JSONResponse TimeSlot

func (response UpdateTimeSlot200JSONResponse) VisitUpdateTimeSlotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// タスク一覧取得
	// (GET /tasks)
	GetTasks(ctx context.Context, request GetTasksRequestObject) (GetTasksResponseObject, error)
	// タスク作成
	// (POST /tasks)
	CreateTask(ctx context.Context, request CreateTaskRequestObject) (CreateTaskResponseObject, error)
	// タスク削除
	// (DELETE /tasks/{taskId})
	DeleteTask(ctx context.Context, request DeleteTaskRequestObject) (DeleteTaskResponseObject, error)
	// タスク詳細取得
	// (GET /tasks/{taskId})
	GetTask(ctx context.Context, request GetTaskRequestObject) (GetTaskResponseObject, error)
	// タスク更新
	// (PUT /tasks/{taskId})
	UpdateTask(ctx context.Context, request UpdateTaskRequestObject) (UpdateTaskResponseObject, error)
	// タイムスロット一覧取得
	// (GET /timeSlots)
	GetTimeSlots(ctx context.Context, request GetTimeSlotsRequestObject) (GetTimeSlotsResponseObject, error)
	// タイムスロット作成
	// (POST /timeSlots)
	CreateTimeSlot(ctx context.Context, request CreateTimeSlotRequestObject) (CreateTimeSlotResponseObject, error)
	// タイムスロット削除
	// (DELETE /timeSlots/{timeSlotId})
	DeleteTimeSlot(ctx context.Context, request DeleteTimeSlotRequestObject) (DeleteTimeSlotResponseObject, error)
	// タイムスロット詳細取得
	// (GET /timeSlots/{timeSlotId})
	GetTimeSlot(ctx context.Context, request GetTimeSlotRequestObject) (GetTimeSlotResponseObject, error)
	// タイムスロット更新
	// (PUT /timeSlots/{timeSlotId})
	UpdateTimeSlot(ctx context.Context, request UpdateTimeSlotRequestObject) (UpdateTimeSlotResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetTasks operation middleware
func (sh *strictHandler) GetTasks(w http.ResponseWriter, r *http.Request, params GetTasksParams) {
	var request GetTasksRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTasks(ctx, request.(GetTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTasks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTasksResponseObject); ok {
		if err := validResponse.VisitGetTasksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTask operation middleware
func (sh *strictHandler) CreateTask(w http.ResponseWriter, r *http.Request) {
	var request CreateTaskRequestObject

	var body CreateTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTask(ctx, request.(CreateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTaskResponseObject); ok {
		if err := validResponse.VisitCreateTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTask operation middleware
func (sh *strictHandler) DeleteTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID) {
	var request DeleteTaskRequestObject

	request.TaskId = taskId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTask(ctx, request.(DeleteTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTaskResponseObject); ok {
		if err := validResponse.VisitDeleteTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTask operation middleware
func (sh *strictHandler) GetTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID) {
	var request GetTaskRequestObject

	request.TaskId = taskId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTask(ctx, request.(GetTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTaskResponseObject); ok {
		if err := validResponse.VisitGetTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTask operation middleware
func (sh *strictHandler) UpdateTask(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID) {
	var request UpdateTaskRequestObject

	request.TaskId = taskId

	var body UpdateTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTask(ctx, request.(UpdateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTaskResponseObject); ok {
		if err := validResponse.VisitUpdateTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTimeSlots operation middleware
func (sh *strictHandler) GetTimeSlots(w http.ResponseWriter, r *http.Request, params GetTimeSlotsParams) {
	var request GetTimeSlotsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTimeSlots(ctx, request.(GetTimeSlotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTimeSlots")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTimeSlotsResponseObject); ok {
		if err := validResponse.VisitGetTimeSlotsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTimeSlot operation middleware
func (sh *strictHandler) CreateTimeSlot(w http.ResponseWriter, r *http.Request) {
	var request CreateTimeSlotRequestObject

	var body CreateTimeSlotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTimeSlot(ctx, request.(CreateTimeSlotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTimeSlot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTimeSlotResponseObject); ok {
		if err := validResponse.VisitCreateTimeSlotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTimeSlot operation middleware
func (sh *strictHandler) DeleteTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID) {
	var request DeleteTimeSlotRequestObject

	request.TimeSlotId = timeSlotId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTimeSlot(ctx, request.(DeleteTimeSlotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTimeSlot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTimeSlotResponseObject); ok {
		if err := validResponse.VisitDeleteTimeSlotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTimeSlot operation middleware
func (sh *strictHandler) GetTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID) {
	var request GetTimeSlotRequestObject

	request.TimeSlotId = timeSlotId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTimeSlot(ctx, request.(GetTimeSlotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTimeSlot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTimeSlotResponseObject); ok {
		if err := validResponse.VisitGetTimeSlotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTimeSlot operation middleware
func (sh *strictHandler) UpdateTimeSlot(w http.ResponseWriter, r *http.Request, timeSlotId openapi_types.UUID) {
	var request UpdateTimeSlotRequestObject

	request.TimeSlotId = timeSlotId

	var body UpdateTimeSlotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTimeSlot(ctx, request.(UpdateTimeSlotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTimeSlot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTimeSlotResponseObject); ok {
		if err := validResponse.VisitUpdateTimeSlotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
