/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ParallelCalendar API
 * ParallelCalendarのバックエンドAPI仕様
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetTasksParams,
  GetTimeSlotsParams,
  Task,
  TimeSlot,
  TimeSlotList
} from '../../model';

import { customInstance } from '../../api/mutator/custom-instance';
import type { ErrorType , BodyType } from '../../api/mutator/custom-instance';
/**
 * @summary タイムスロット一覧取得
 */
export const getTimeSlots = (
    params: GetTimeSlotsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TimeSlotList>(
      {url: `/timeSlots`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetTimeSlotsQueryKey = (params?: GetTimeSlotsParams,) => {
    return [
    `/timeSlots`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTimeSlotsQueryOptions = <TData = Awaited<ReturnType<typeof getTimeSlots>>, TError = ErrorType<unknown>>(params: GetTimeSlotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimeSlots>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTimeSlotsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTimeSlots>>> = ({ signal }) => getTimeSlots(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTimeSlots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTimeSlotsQueryResult = NonNullable<Awaited<ReturnType<typeof getTimeSlots>>>
export type GetTimeSlotsQueryError = ErrorType<unknown>


export function useGetTimeSlots<TData = Awaited<ReturnType<typeof getTimeSlots>>, TError = ErrorType<unknown>>(
 params: GetTimeSlotsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimeSlots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTimeSlots>>,
          TError,
          Awaited<ReturnType<typeof getTimeSlots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTimeSlots<TData = Awaited<ReturnType<typeof getTimeSlots>>, TError = ErrorType<unknown>>(
 params: GetTimeSlotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimeSlots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTimeSlots>>,
          TError,
          Awaited<ReturnType<typeof getTimeSlots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTimeSlots<TData = Awaited<ReturnType<typeof getTimeSlots>>, TError = ErrorType<unknown>>(
 params: GetTimeSlotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimeSlots>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary タイムスロット一覧取得
 */

export function useGetTimeSlots<TData = Awaited<ReturnType<typeof getTimeSlots>>, TError = ErrorType<unknown>>(
 params: GetTimeSlotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimeSlots>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTimeSlotsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary タイムスロット作成
 */
export const createTimeSlot = (
    timeSlot: BodyType<TimeSlot>,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TimeSlot>(
      {url: `/timeSlots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: timeSlot, signal
    },
      );
    }
  


export const getCreateTimeSlotMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTimeSlot>>, TError,{data: BodyType<TimeSlot>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTimeSlot>>, TError,{data: BodyType<TimeSlot>}, TContext> => {

const mutationKey = ['createTimeSlot'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTimeSlot>>, {data: BodyType<TimeSlot>}> = (props) => {
          const {data} = props ?? {};

          return  createTimeSlot(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTimeSlotMutationResult = NonNullable<Awaited<ReturnType<typeof createTimeSlot>>>
    export type CreateTimeSlotMutationBody = BodyType<TimeSlot>
    export type CreateTimeSlotMutationError = ErrorType<unknown>

    /**
 * @summary タイムスロット作成
 */
export const useCreateTimeSlot = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTimeSlot>>, TError,{data: BodyType<TimeSlot>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTimeSlot>>,
        TError,
        {data: BodyType<TimeSlot>},
        TContext
      > => {

      const mutationOptions = getCreateTimeSlotMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary タイムスロット詳細取得
 */
export const getTimeSlot = (
    timeSlotId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TimeSlot>(
      {url: `/timeSlots/${timeSlotId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetTimeSlotQueryKey = (timeSlotId?: string,) => {
    return [
    `/timeSlots/${timeSlotId}`
    ] as const;
    }

    
export const getGetTimeSlotQueryOptions = <TData = Awaited<ReturnType<typeof getTimeSlot>>, TError = ErrorType<unknown>>(timeSlotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimeSlot>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTimeSlotQueryKey(timeSlotId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTimeSlot>>> = ({ signal }) => getTimeSlot(timeSlotId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(timeSlotId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTimeSlot>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTimeSlotQueryResult = NonNullable<Awaited<ReturnType<typeof getTimeSlot>>>
export type GetTimeSlotQueryError = ErrorType<unknown>


export function useGetTimeSlot<TData = Awaited<ReturnType<typeof getTimeSlot>>, TError = ErrorType<unknown>>(
 timeSlotId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimeSlot>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTimeSlot>>,
          TError,
          Awaited<ReturnType<typeof getTimeSlot>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTimeSlot<TData = Awaited<ReturnType<typeof getTimeSlot>>, TError = ErrorType<unknown>>(
 timeSlotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimeSlot>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTimeSlot>>,
          TError,
          Awaited<ReturnType<typeof getTimeSlot>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTimeSlot<TData = Awaited<ReturnType<typeof getTimeSlot>>, TError = ErrorType<unknown>>(
 timeSlotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimeSlot>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary タイムスロット詳細取得
 */

export function useGetTimeSlot<TData = Awaited<ReturnType<typeof getTimeSlot>>, TError = ErrorType<unknown>>(
 timeSlotId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimeSlot>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTimeSlotQueryOptions(timeSlotId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary タイムスロット更新
 */
export const updateTimeSlot = (
    timeSlotId: string,
    timeSlot: BodyType<TimeSlot>,
 ) => {
      
      
      return customInstance<TimeSlot>(
      {url: `/timeSlots/${timeSlotId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: timeSlot
    },
      );
    }
  


export const getUpdateTimeSlotMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTimeSlot>>, TError,{timeSlotId: string;data: BodyType<TimeSlot>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTimeSlot>>, TError,{timeSlotId: string;data: BodyType<TimeSlot>}, TContext> => {

const mutationKey = ['updateTimeSlot'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTimeSlot>>, {timeSlotId: string;data: BodyType<TimeSlot>}> = (props) => {
          const {timeSlotId,data} = props ?? {};

          return  updateTimeSlot(timeSlotId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTimeSlotMutationResult = NonNullable<Awaited<ReturnType<typeof updateTimeSlot>>>
    export type UpdateTimeSlotMutationBody = BodyType<TimeSlot>
    export type UpdateTimeSlotMutationError = ErrorType<unknown>

    /**
 * @summary タイムスロット更新
 */
export const useUpdateTimeSlot = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTimeSlot>>, TError,{timeSlotId: string;data: BodyType<TimeSlot>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTimeSlot>>,
        TError,
        {timeSlotId: string;data: BodyType<TimeSlot>},
        TContext
      > => {

      const mutationOptions = getUpdateTimeSlotMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary タイムスロット削除
 */
export const deleteTimeSlot = (
    timeSlotId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/timeSlots/${timeSlotId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteTimeSlotMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTimeSlot>>, TError,{timeSlotId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTimeSlot>>, TError,{timeSlotId: string}, TContext> => {

const mutationKey = ['deleteTimeSlot'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTimeSlot>>, {timeSlotId: string}> = (props) => {
          const {timeSlotId} = props ?? {};

          return  deleteTimeSlot(timeSlotId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTimeSlotMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTimeSlot>>>
    
    export type DeleteTimeSlotMutationError = ErrorType<unknown>

    /**
 * @summary タイムスロット削除
 */
export const useDeleteTimeSlot = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTimeSlot>>, TError,{timeSlotId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTimeSlot>>,
        TError,
        {timeSlotId: string},
        TContext
      > => {

      const mutationOptions = getDeleteTimeSlotMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary タスク一覧取得
 */
export const getTasks = (
    params: GetTasksParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Task[]>(
      {url: `/tasks`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetTasksQueryKey = (params?: GetTasksParams,) => {
    return [
    `/tasks`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTasksQueryOptions = <TData = Awaited<ReturnType<typeof getTasks>>, TError = ErrorType<unknown>>(params: GetTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTasksQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasks>>> = ({ signal }) => getTasks(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getTasks>>>
export type GetTasksQueryError = ErrorType<unknown>


export function useGetTasks<TData = Awaited<ReturnType<typeof getTasks>>, TError = ErrorType<unknown>>(
 params: GetTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasks>>,
          TError,
          Awaited<ReturnType<typeof getTasks>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTasks<TData = Awaited<ReturnType<typeof getTasks>>, TError = ErrorType<unknown>>(
 params: GetTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasks>>,
          TError,
          Awaited<ReturnType<typeof getTasks>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTasks<TData = Awaited<ReturnType<typeof getTasks>>, TError = ErrorType<unknown>>(
 params: GetTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary タスク一覧取得
 */

export function useGetTasks<TData = Awaited<ReturnType<typeof getTasks>>, TError = ErrorType<unknown>>(
 params: GetTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTasksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary タスク作成
 */
export const createTask = (
    task: BodyType<Task>,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Task>(
      {url: `/tasks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: task, signal
    },
      );
    }
  


export const getCreateTaskMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,{data: BodyType<Task>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,{data: BodyType<Task>}, TContext> => {

const mutationKey = ['createTask'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTask>>, {data: BodyType<Task>}> = (props) => {
          const {data} = props ?? {};

          return  createTask(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTaskMutationResult = NonNullable<Awaited<ReturnType<typeof createTask>>>
    export type CreateTaskMutationBody = BodyType<Task>
    export type CreateTaskMutationError = ErrorType<unknown>

    /**
 * @summary タスク作成
 */
export const useCreateTask = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTask>>, TError,{data: BodyType<Task>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTask>>,
        TError,
        {data: BodyType<Task>},
        TContext
      > => {

      const mutationOptions = getCreateTaskMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary タスク詳細取得
 */
export const getTask = (
    taskId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Task>(
      {url: `/tasks/${taskId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetTaskQueryKey = (taskId?: string,) => {
    return [
    `/tasks/${taskId}`
    ] as const;
    }

    
export const getGetTaskQueryOptions = <TData = Awaited<ReturnType<typeof getTask>>, TError = ErrorType<Error>>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTask>>> = ({ signal }) => getTask(taskId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskQueryResult = NonNullable<Awaited<ReturnType<typeof getTask>>>
export type GetTaskQueryError = ErrorType<Error>


export function useGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = ErrorType<Error>>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTask>>,
          TError,
          Awaited<ReturnType<typeof getTask>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = ErrorType<Error>>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTask>>,
          TError,
          Awaited<ReturnType<typeof getTask>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = ErrorType<Error>>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary タスク詳細取得
 */

export function useGetTask<TData = Awaited<ReturnType<typeof getTask>>, TError = ErrorType<Error>>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaskQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary タスク更新
 */
export const updateTask = (
    taskId: string,
    task: BodyType<Task>,
 ) => {
      
      
      return customInstance<Task>(
      {url: `/tasks/${taskId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: task
    },
      );
    }
  


export const getUpdateTaskMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,{taskId: string;data: BodyType<Task>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,{taskId: string;data: BodyType<Task>}, TContext> => {

const mutationKey = ['updateTask'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTask>>, {taskId: string;data: BodyType<Task>}> = (props) => {
          const {taskId,data} = props ?? {};

          return  updateTask(taskId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTaskMutationResult = NonNullable<Awaited<ReturnType<typeof updateTask>>>
    export type UpdateTaskMutationBody = BodyType<Task>
    export type UpdateTaskMutationError = ErrorType<unknown>

    /**
 * @summary タスク更新
 */
export const useUpdateTask = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,{taskId: string;data: BodyType<Task>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTask>>,
        TError,
        {taskId: string;data: BodyType<Task>},
        TContext
      > => {

      const mutationOptions = getUpdateTaskMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary タスク削除
 */
export const deleteTask = (
    taskId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/tasks/${taskId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteTaskMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,{taskId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,{taskId: string}, TContext> => {

const mutationKey = ['deleteTask'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTask>>, {taskId: string}> = (props) => {
          const {taskId} = props ?? {};

          return  deleteTask(taskId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTaskMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTask>>>
    
    export type DeleteTaskMutationError = ErrorType<unknown>

    /**
 * @summary タスク削除
 */
export const useDeleteTask = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTask>>, TError,{taskId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTask>>,
        TError,
        {taskId: string},
        TContext
      > => {

      const mutationOptions = getDeleteTaskMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
