/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ParallelCalendar API
 * ParallelCalendarのバックエンドAPI仕様
 * OpenAPI spec version: 1.0.0
 */

export interface Task {
  taskId: string;
  userId: string;
  title: string;
  taskDescription?: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
}
