/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ParallelCalendar API
 * ParallelCalendarのバックエンドAPI仕様
 * OpenAPI spec version: 1.0.0
 */
import type { TimeSlotExtData } from './timeSlotExtData';

export interface TimeSlot {
  /** タイムスロットID */
  timeSlotId: string;
  /** ユーザーID (Email) */
  userId: string;
  /** 紐づくタスクID */
  taskId: string;
  /** アロケーション */
  allocation: string;
  /** 拡張データ */
  extData?: TimeSlotExtData;
  startAt: string;
  endAt: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
}
