// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MUser struct {
	UserID    pgtype.UUID
	UserName  string
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

type TTask struct {
	TaskID          pgtype.UUID
	UserID          pgtype.UUID
	Title           string
	TaskDescription string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	CreatedBy       pgtype.UUID
	UpdatedBy       pgtype.UUID
}

type TTimeSlot struct {
	TimeSlotID pgtype.UUID
	UserID     pgtype.UUID
	TaskID     pgtype.UUID
	Allocation string
	StartAt    pgtype.Timestamp
	EndAt      pgtype.Timestamp
	ExtData    []byte
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	CreatedBy  pgtype.UUID
	UpdatedBy  pgtype.UUID
}
