// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO t_task (
  task_id,
  user_id,
  title,
  task_description,
  created_at,
  updated_at,
  created_by,
  updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING task_id, user_id, title, task_description, created_at, updated_at, created_by, updated_by
`

type CreateTaskParams struct {
	TaskID          pgtype.UUID
	UserID          pgtype.UUID
	Title           string
	TaskDescription pgtype.Text
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	CreatedBy       pgtype.UUID
	UpdatedBy       pgtype.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (TTask, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.TaskID,
		arg.UserID,
		arg.Title,
		arg.TaskDescription,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i TTask
	err := row.Scan(
		&i.TaskID,
		&i.UserID,
		&i.Title,
		&i.TaskDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const createTimeSlot = `-- name: CreateTimeSlot :one
INSERT INTO t_time_slot (
  time_slot_id,
  user_id,
  task_id,
  allocation,
  start_at,
  end_at,
  ext_data,
  created_at,
  updated_at,
  created_by,
  updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING time_slot_id, user_id, task_id, allocation, start_at, end_at, ext_data, created_at, updated_at, created_by, updated_by
`

type CreateTimeSlotParams struct {
	TimeSlotID pgtype.UUID
	UserID     pgtype.UUID
	TaskID     pgtype.UUID
	Allocation string
	StartAt    pgtype.Timestamp
	EndAt      pgtype.Timestamp
	ExtData    []byte
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	CreatedBy  pgtype.UUID
	UpdatedBy  pgtype.UUID
}

func (q *Queries) CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (TTimeSlot, error) {
	row := q.db.QueryRow(ctx, createTimeSlot,
		arg.TimeSlotID,
		arg.UserID,
		arg.TaskID,
		arg.Allocation,
		arg.StartAt,
		arg.EndAt,
		arg.ExtData,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i TTimeSlot
	err := row.Scan(
		&i.TimeSlotID,
		&i.UserID,
		&i.TaskID,
		&i.Allocation,
		&i.StartAt,
		&i.EndAt,
		&i.ExtData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO m_user (
  user_id, user_name, email, created_at, updated_at, created_by, updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING user_id, user_name, email, created_at, updated_at, created_by, updated_by
`

type CreateUserParams struct {
	UserID    pgtype.UUID
	UserName  string
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (MUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.UserName,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i MUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM t_task
WHERE task_id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, taskID)
	return err
}

const deleteTimeSlot = `-- name: DeleteTimeSlot :exec
DELETE FROM t_time_slot
WHERE time_slot_id = $1
`

func (q *Queries) DeleteTimeSlot(ctx context.Context, timeSlotID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimeSlot, timeSlotID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT task_id, user_id, title, task_description, created_at, updated_at, created_by, updated_by
FROM t_task
WHERE task_id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, taskID pgtype.UUID) (TTask, error) {
	row := q.db.QueryRow(ctx, getTask, taskID)
	var i TTask
	err := row.Scan(
		&i.TaskID,
		&i.UserID,
		&i.Title,
		&i.TaskDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT task_id, user_id, title, task_description, created_at, updated_at, created_by, updated_by
FROM t_task
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTasks(ctx context.Context, userID pgtype.UUID) ([]TTask, error) {
	rows, err := q.db.Query(ctx, getTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TTask
	for rows.Next() {
		var i TTask
		if err := rows.Scan(
			&i.TaskID,
			&i.UserID,
			&i.Title,
			&i.TaskDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeSlot = `-- name: GetTimeSlot :one
SELECT time_slot_id, user_id, task_id, allocation, start_at, end_at, ext_data, created_at, updated_at, created_by, updated_by
FROM t_time_slot
WHERE time_slot_id = $1 LIMIT 1
`

func (q *Queries) GetTimeSlot(ctx context.Context, timeSlotID pgtype.UUID) (TTimeSlot, error) {
	row := q.db.QueryRow(ctx, getTimeSlot, timeSlotID)
	var i TTimeSlot
	err := row.Scan(
		&i.TimeSlotID,
		&i.UserID,
		&i.TaskID,
		&i.Allocation,
		&i.StartAt,
		&i.EndAt,
		&i.ExtData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getTimeSlots = `-- name: GetTimeSlots :many
SELECT time_slot_id, user_id, task_id, allocation, start_at, end_at, ext_data, created_at, updated_at, created_by, updated_by
FROM t_time_slot
WHERE user_id = $1
  AND start_at >= $2
  AND end_at <= $3
ORDER BY start_at ASC
`

type GetTimeSlotsParams struct {
	UserID  pgtype.UUID
	StartAt pgtype.Timestamp
	EndAt   pgtype.Timestamp
}

func (q *Queries) GetTimeSlots(ctx context.Context, arg GetTimeSlotsParams) ([]TTimeSlot, error) {
	rows, err := q.db.Query(ctx, getTimeSlots, arg.UserID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TTimeSlot
	for rows.Next() {
		var i TTimeSlot
		if err := rows.Scan(
			&i.TimeSlotID,
			&i.UserID,
			&i.TaskID,
			&i.Allocation,
			&i.StartAt,
			&i.EndAt,
			&i.ExtData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT user_id, user_name, email, created_at, updated_at, created_by, updated_by FROM m_user
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID pgtype.UUID) (MUser, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i MUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, user_name, email, created_at, updated_at, created_by, updated_by FROM m_user
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (MUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i MUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE t_task
SET 
  title = $2,
  task_description = $3,
  updated_at = $4,
  updated_by = $5
WHERE task_id = $1
RETURNING task_id, user_id, title, task_description, created_at, updated_at, created_by, updated_by
`

type UpdateTaskParams struct {
	TaskID          pgtype.UUID
	Title           string
	TaskDescription pgtype.Text
	UpdatedAt       pgtype.Timestamp
	UpdatedBy       pgtype.UUID
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (TTask, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.TaskID,
		arg.Title,
		arg.TaskDescription,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i TTask
	err := row.Scan(
		&i.TaskID,
		&i.UserID,
		&i.Title,
		&i.TaskDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateTimeSlot = `-- name: UpdateTimeSlot :one
UPDATE t_time_slot
SET 
  task_id = $2,
  allocation = $3,
  start_at = $4,
  end_at = $5,
  ext_data = $6,
  updated_at = $7,
  updated_by = $8
WHERE time_slot_id = $1
RETURNING time_slot_id, user_id, task_id, allocation, start_at, end_at, ext_data, created_at, updated_at, created_by, updated_by
`

type UpdateTimeSlotParams struct {
	TimeSlotID pgtype.UUID
	TaskID     pgtype.UUID
	Allocation string
	StartAt    pgtype.Timestamp
	EndAt      pgtype.Timestamp
	ExtData    []byte
	UpdatedAt  pgtype.Timestamp
	UpdatedBy  pgtype.UUID
}

func (q *Queries) UpdateTimeSlot(ctx context.Context, arg UpdateTimeSlotParams) (TTimeSlot, error) {
	row := q.db.QueryRow(ctx, updateTimeSlot,
		arg.TimeSlotID,
		arg.TaskID,
		arg.Allocation,
		arg.StartAt,
		arg.EndAt,
		arg.ExtData,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i TTimeSlot
	err := row.Scan(
		&i.TimeSlotID,
		&i.UserID,
		&i.TaskID,
		&i.Allocation,
		&i.StartAt,
		&i.EndAt,
		&i.ExtData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
